import { PageSchema } from "@/types/schema";

export const aboutPageSchema: PageSchema = {
  id: "about-page",
  name: "About Us Page",
  slug: "/about",
  description: "About page with company information and values",
  icon: "Users",
  settings: {
    enableSectionReordering: true,
    enableSectionToggle: true,
  },
  sections: [
    {
      id: "hero",
      name: "Hero Section",
      description: "About page hero banner",
      icon: "Image",
      order: 0,
      enabled: true,
      fields: [
        {
          name: "sectionTitle",
          label: "Section Title",
          type: "text",
        },
        {
          name: "title",
          label: "Main Title",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          rows: 4,
        },
        {
          name: "descriptionMaxWidth",
          label: "Description Max Width (pixels)",
          type: "number",
          min: 300,
          max: 1200,
        },
        {
          name: "backgroundImages",
          label: "Background Images",
          type: "images",
          maxItems: 10,
        },
        {
          name: "overlayColor",
          label: "Overlay Color",
          type: "color",
          description: "Color overlay on background (e.g., #180330B2 for rgba)",
        },
      ],
    },
    {
      id: "philosophy",
      name: "Philosophy Section",
      description: "Our philosophy and approach",
      icon: "Lightbulb",
      order: 1,
      enabled: true,
      fields: [
        {
          name: "sectionTitle",
          label: "Section Title",
          type: "text",
        },
        {
          name: "heading",
          label: "Heading",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          rows: 4,
        },
        {
          name: "items",
          label: "Philosophy Items",
          type: "array",
          description: "Key philosophy points",
          itemType: {
            name: "philosophyItem",
            label: "Philosophy Item",
            type: "object",
            fields: [
              {
                name: "title",
                label: "Title",
                type: "text",
                required: true,
              },
              {
                name: "description",
                label: "Description",
                type: "textarea",
                rows: 3,
              },
            ],
          },
        },
      ],
    },
    {
      id: "what-we-do",
      name: "What We Do Section",
      description: "Our services and offerings",
      icon: "Briefcase",
      order: 2,
      enabled: true,
      fields: [
        {
          name: "heading",
          label: "Heading",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          rows: 4,
        },
        {
          name: "cardBackground",
          label: "Card Background",
          type: "text",
          description: "CSS gradient or color (e.g., radial-gradient(...))",
        },
        {
          name: "cardTitleColor",
          label: "Card Title Color",
          type: "color",
        },
        {
          name: "cardDescriptionColor",
          label: "Card Description Color",
          type: "color",
        },
        {
          name: "iconBackgroundColor",
          label: "Icon Background Color",
          type: "color",
        },
        {
          name: "items",
          label: "Service Items",
          type: "array",
          description: "List of services",
          itemType: {
            name: "serviceItem",
            label: "Service Item",
            type: "object",
            fields: [
              {
                name: "title",
                label: "Title",
                type: "text",
                required: true,
              },
              {
                name: "description",
                label: "Description",
                type: "textarea",
                rows: 3,
              },
              {
                name: "iconSvg",
                label: "Icon SVG",
                type: "textarea",
                rows: 10,
                description: "Full SVG code",
              },
              {
                name: "isSpecial",
                label: "Is Special (FlexiBrez style)",
                type: "boolean",
              },
            ],
          },
        },
      ],
    },
    {
      id: "studio-values",
      name: "Studio Values Section",
      description: "Core values and principles",
      icon: "Heart",
      order: 3,
      enabled: true,
      fields: [
        {
          name: "heading",
          label: "Heading",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          rows: 3,
        },
        {
          name: "iconBackground",
          label: "Icon Background",
          type: "text",
          description: "CSS gradient (e.g., radial-gradient(...))",
        },
        {
          name: "valueTitleColor",
          label: "Value Title Color",
          type: "color",
        },
        {
          name: "values",
          label: "Values",
          type: "array",
          description: "Core values",
          itemType: {
            name: "value",
            label: "Value",
            type: "object",
            fields: [
              {
                name: "title",
                label: "Value Title",
                type: "text",
                required: true,
              },
              {
                name: "iconSvg",
                label: "Icon SVG",
                type: "textarea",
                rows: 10,
                description: "Full SVG code for icon",
              },
            ],
          },
        },
      ],
    },
    {
      id: "mon-adams",
      name: "Mon Adams Section",
      description: "Founder/team member spotlight",
      icon: "User",
      order: 4,
      enabled: true,
      fields: [
        {
          name: "name",
          label: "Name",
          type: "text",
          required: true,
        },
        {
          name: "title",
          label: "Title/Role",
          type: "text",
        },
        {
          name: "bio",
          label: "Biography",
          type: "textarea",
          rows: 5,
        },
        {
          name: "image",
          label: "Photo",
          type: "image",
        },
        {
          name: "backgroundImage",
          label: "Background Decorative Image",
          type: "image",
        },
        {
          name: "quote",
          label: "Quote",
          type: "text",
        },
        {
          name: "headingColor",
          label: "Name Color",
          type: "color",
        },
        {
          name: "bioColor",
          label: "Bio/Title Text Color",
          type: "color",
        },
        {
          name: "quoteColor",
          label: "Quote Text Color",
          type: "color",
        },
        {
          name: "cards",
          label: "Category Cards",
          type: "array",
          description: "Cards showing categories/highlights",
          itemType: {
            name: "monadamsCard",
            label: "Card",
            type: "object",
            fields: [
              {
                name: "icon",
                label: "Icon Image URL",
                type: "url",
              },
              {
                name: "text",
                label: "Card Text",
                type: "text",
                required: true,
              },
              {
                name: "gradient",
                label: "Background Gradient",
                type: "text",
                description: "CSS gradient (e.g., linear-gradient(135deg, #FCE7F3 0%, #FCCEE8 100%))",
              },
            ],
          },
        },
        {
          name: "cardTextColor",
          label: "Card Text Color",
          type: "color",
        },
        {
          name: "cardBackgroundColor",
          label: "Card Background Color",
          type: "color",
        },
        {
          name: "cardBorderColor",
          label: "Card Border Color",
          type: "text",
          description: "CSS color including rgba",
        },
      ],
    },
    {
      id: "how-we-work",
      name: "How We Work Section",
      description: "Our process and methodology",
      icon: "Workflow",
      order: 5,
      enabled: true,
      fields: [
        {
          name: "heading",
          label: "Section Heading",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Section Description",
          type: "textarea",
          rows: 3,
        },
        {
          name: "headingColor",
          label: "Heading Color",
          type: "color",
        },
        {
          name: "descriptionColor",
          label: "Description Color",
          type: "color",
        },
        {
          name: "steps",
          label: "Process Steps",
          type: "array",
          description: "Step-by-step process",
          itemType: {
            name: "step",
            label: "Step",
            type: "object",
            fields: [
              {
                name: "title",
                label: "Step Title",
                type: "text",
                required: true,
              },
              {
                name: "subheading",
                label: "Step Subheading",
                type: "text",
              },
              {
                name: "description",
                label: "Step Description",
                type: "textarea",
                rows: 3,
              },
              {
                name: "iconSvg",
                label: "Step Icon SVG",
                type: "textarea",
                rows: 10,
                description: "Full SVG code",
              },
            ],
          },
        },
        {
          name: "stepTitleColor",
          label: "Step Title Color",
          type: "color",
        },
        {
          name: "stepSubheadingColor",
          label: "Step Subheading Color",
          type: "color",
        },
        {
          name: "stepDescriptionColor",
          label: "Step Description Color",
          type: "color",
        },
        {
          name: "iconContainerBackground",
          label: "Icon Container Background",
          type: "color",
        },
        {
          name: "iconContainerBorderColor",
          label: "Icon Container Border Color",
          type: "color",
        },
        {
          name: "iconColor",
          label: "Icon Color",
          type: "color",
        },
        {
          name: "arrowColor",
          label: "Arrow Color",
          type: "color",
        },
      ],
    },
    {
      id: "studio-cards",
      name: "Studio Cards Section",
      description: "Customizable studio cards with backgrounds, gradients, and buttons",
      icon: "LayoutGrid",
      order: 6,
      enabled: true,
      fields: [
        {
          name: "cards",
          label: "Studio Cards",
          type: "array",
          description: "Add and configure studio cards",
          itemType: {
            name: "studioCard",
            label: "Studio Card",
            type: "object",
            fields: [
              {
                name: "type",
                label: "Card Type",
                type: "select",
                required: true,
                options: [
                  { label: "Image with Overlay", value: "image-overlay" },
                  { label: "Gradient Background", value: "gradient" },
                ],
              },
              {
                name: "title",
                label: "Card Title",
                type: "text",
                required: true,
              },
              {
                name: "backgroundColor",
                label: "Base Background Color",
                type: "color",
              },
              {
                name: "backgroundImage",
                label: "Background Image (for image-overlay)",
                type: "image",
              },
              {
                name: "imagePosition",
                label: "Image Position",
                type: "select",
                options: [
                  { label: "Left Center", value: "left center" },
                  { label: "Center", value: "center" },
                  { label: "Right Center", value: "right center" },
                  { label: "15% Left", value: "15% center" },
                  { label: "30% Left", value: "30% center" },
                  { label: "Custom", value: "custom" },
                ],
              },
              {
                name: "overlayOpacity",
                label: "Overlay Opacity",
                type: "number",
                min: 0,
                max: 1,
                step: 0.1,
              },
              {
                name: "gradientStart",
                label: "Gradient Start Color (for gradient)",
                type: "color",
              },
              {
                name: "gradientEnd",
                label: "Gradient End Color (for gradient)",
                type: "color",
              },
              {
                name: "gradientAngle",
                label: "Gradient Angle (degrees)",
                type: "number",
                min: 0,
                max: 360,
              },
              {
                name: "titleColor",
                label: "Title Text Color",
                type: "color",
              },
              {
                name: "titleFontSize",
                label: "Title Font Size",
                type: "text",
                description: "CSS value (e.g., clamp(18px, 3vw, 22px))",
              },
              {
                name: "titleFontFamily",
                label: "Title Font Family",
                type: "select",
                options: [
                  { label: "Bona Nova", value: "var(--font-bona-nova)" },
                  { label: "Arial", value: "Arial, sans-serif" },
                  { label: "Inter", value: "var(--font-inter)" },
                ],
              },
              {
                name: "minHeight",
                label: "Card Min Height",
                type: "text",
                description: "CSS value (e.g., 180px)",
              },
              {
                name: "padding",
                label: "Card Padding",
                type: "text",
                description: "CSS value",
              },
              {
                name: "alignment",
                label: "Content Alignment",
                type: "select",
                options: [
                  { label: "Center", value: "center" },
                  { label: "Start", value: "start" },
                  { label: "End", value: "end" },
                ],
              },
              {
                name: "buttons",
                label: "Buttons",
                type: "array",
                description: "Card action buttons",
                itemType: {
                  name: "button",
                  label: "Button",
                  type: "object",
                  fields: [
                    {
                      name: "text",
                      label: "Button Text",
                      type: "text",
                      required: true,
                    },
                    {
                      name: "link",
                      label: "Button Link",
                      type: "url",
                    },
                    {
                      name: "backgroundColor",
                      label: "Background Color",
                      type: "color",
                    },
                    {
                      name: "textColor",
                      label: "Text Color",
                      type: "color",
                    },
                    {
                      name: "fontFamily",
                      label: "Font Family",
                      type: "select",
                      options: [
                        { label: "Arial", value: "Arial, sans-serif" },
                        { label: "Inter", value: "var(--font-inter)" },
                        { label: "Bona Nova", value: "var(--font-bona-nova)" },
                      ],
                    },
                    {
                      name: "fontSize",
                      label: "Font Size",
                      type: "text",
                      description: "CSS value",
                    },
                    {
                      name: "isHighlighted",
                      label: "Is Highlighted",
                      type: "boolean",
                      description: "Use highlight styling",
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  ],
};
