import { PageSchema } from "@/types/schema";

export const landingPageSchema: PageSchema = {
  id: "landing-page",
  name: "Landing Page",
  slug: "/",
  description: "Home page of the website",
  icon: "Home",
  settings: {
    enableSectionReordering: true,
    enableSectionToggle: true,
  },
  sections: [
    {
      id: "hero",
      name: "Hero Section",
      description: "Main hero banner at the top of the page",
      icon: "Image",
      order: 0,
      enabled: true,
      fields: [
        {
          name: "sectionTitle",
          label: "Section Title",
          type: "text",
          description: "Small text above the main title (e.g., 'UTTER LORE')",
          placeholder: "Enter section title",
          defaultValue: "UTTER LORE",
        },
        {
          name: "title",
          label: "Main Title",
          type: "text",
          description: "The main headline of the hero section",
          required: true,
          placeholder: "Enter main headline",
          defaultValue: "EMPOWERING KNOWLEDGE FOR THE MINDFUL COLLECTIVES",
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          description: "Supporting text below the title",
          rows: 3,
          placeholder: "Enter description text",
          defaultValue:
            "Where design meets storytelling. Explore insights, ideas, and reflections across beauty, fashion, and lifestyle.",
        },
        {
          name: "primaryButton",
          label: "Primary Button",
          type: "group",
          collapsible: true,
          fields: [
            {
              name: "text",
              label: "Button Text",
              type: "text",
              placeholder: "e.g., Explore Our Stories",
              defaultValue: "Explore Our Stories",
            },
            {
              name: "link",
              label: "Button Link",
              type: "url",
              placeholder: "/stories",
              defaultValue: "/stories",
            },
            {
              name: "backgroundColor",
              label: "Background Color",
              type: "color",
              description: "Button background color",
              placeholder: "e.g., #000000 or rgba(0,0,0,1)",
              defaultValue: "#000000",
            },
            {
              name: "textColor",
              label: "Text Color",
              type: "color",
              description: "Button text color",
              placeholder: "e.g., #FFFFFF or rgba(255,255,255,1)",
              defaultValue: "#FFFFFF",
            },
            {
              name: "enabled",
              label: "Show Button",
              type: "boolean",
              defaultValue: true,
            },
          ],
        },
        {
          name: "secondaryButton",
          label: "Secondary Button",
          type: "group",
          collapsible: true,
          fields: [
            {
              name: "text",
              label: "Button Text",
              type: "text",
              placeholder: "e.g., Learn More",
            },
            {
              name: "link",
              label: "Button Link",
              type: "url",
              placeholder: "/about",
            },
            {
              name: "backgroundColor",
              label: "Background Color",
              type: "color",
              description: "Button background color",
              placeholder: "e.g., #FFFFFF or rgba(255,255,255,0.1)",
              defaultValue: "transparent",
            },
            {
              name: "textColor",
              label: "Text Color",
              type: "color",
              description: "Button text color",
              placeholder: "e.g., #FFFFFF or rgba(255,255,255,1)",
              defaultValue: "#FFFFFF",
            },
            {
              name: "borderColor",
              label: "Border Color",
              type: "color",
              description: "Button border color (for outline style)",
              placeholder: "e.g., #FFFFFF",
              defaultValue: "#FFFFFF",
            },
            {
              name: "enabled",
              label: "Show Button",
              type: "boolean",
              defaultValue: false,
            },
          ],
        },
        {
          name: "backgroundImages",
          label: "Background Images",
          type: "images",
          description:
            "Images for the background carousel. Add multiple for slideshow effect.",
          maxItems: 10,
          defaultValue: ["/assets/images/CarasoulWallpaper.jpg"],
        },
        {
          name: "overlayColor",
          label: "Overlay Color",
          type: "color",
          description: "Color overlay on the background image",
          defaultValue: "rgba(0, 0, 0, 0.5)",
        },
      ],
    },
    {
      id: "about-preview",
      name: "About Us Preview",
      description: "Brief about section on the landing page",
      icon: "Users",
      order: 1,
      enabled: true,
      fields: [
        {
          name: "sectionTitle",
          label: "Section Title",
          type: "text",
          defaultValue: "About",
        },
        {
          name: "heading",
          label: "Heading",
          type: "text",
          defaultValue: "UTTER LORE",
        },
        {
          name: "content",
          label: "Content Paragraphs",
          type: "array",
          description: "Add multiple paragraphs of content",
          itemType: {
            name: "paragraph",
            label: "Paragraph",
            type: "textarea",
            rows: 3,
          },
          defaultValue: [
            "Utter Lore stands as a visionary entity, seamlessly blending creativity with purpose to craft experiences that transcend the ordinary.",
            "From curated fashion insights and thoughtful lifestyle narratives to transformative beauty explorations, Utter Lore redefines the way we engage with the world around us.",
            "At its core, Utter Lore is not just a brand—it is a movement.",
          ],
        },
        {
          name: "buttonText",
          label: "Button Text",
          type: "text",
          defaultValue: "Read Our Story",
        },
        {
          name: "buttonLink",
          label: "Button Link",
          type: "url",
          defaultValue: "/about",
        },
        {
          name: "image",
          label: "Image",
          type: "image",
          defaultValue: "/assets/images/AboutUs.png",
        },
        {
          name: "imagePosition",
          label: "Image Position",
          type: "select",
          options: [
            { label: "Left", value: "left" },
            { label: "Right", value: "right" },
          ],
          defaultValue: "left",
        },
      ],
    },
  ],
};
